dbt_sales:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: data_eng
      password: data_eng
      port: 5433
      dbname: sales_db
      schema: public
      threads: 2
